import "./audiophile.css";

export const metadata = {
  title: "Frontend Mentor | Audiophile e-commerce website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="icon" type="image/png" sizes="32x32" href="./assets/favicon-32x32.png"/>
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
